### DISCUSSION TITLE
如何配置多个执行器

### DISCUSSION THREAD

**Discussion by quant1box** [wondertrader/wondertrader#47] [Q&A] [answered]
在查阅官方和半官方的文档时，和代码对比发现有些出入，我懵逼了，一时不知道如何配置多个执行器，前来请教大佬给予指点。也希望大佬们能尽快完善相关文档，能让我等小白赶紧学习入手实盘。感谢！！！

**Comment by wondertrader** [comment, marked as answer]
请参考以下代码
```yaml
executers:
-   active: true    #是否启用
    id: exec1        #执行器id，不可重复
    trader: simnow1  #执行器绑定的交易通道id，如果不存在，无法执行
    scale: 1        #数量放大倍数，即该执行器的目标仓位，是组合理论目标仓位的多少倍，可以为小数 

    policy:         #执行单元分配策略，系统根据该策略创建对一个的执行单元
        default:    #默认策略，根据品种ID设置，如SHFE.rb，如果没有针对品种设置，则使用默认策略
            name: WtExeFact.WtMinImpactExeUnit #执行单元名称
            offset: 0       #委托价偏移跳数
            expire: 5       #订单超时没秒数
            pricemode: 1    #基础价格模式，-1-己方最优，0-最新价，1-对手价
            span: 500       #下单时间间隔（tick驱动的）
            byrate: false   #是否按对手盘挂单量的比例挂单，配合rate使用
            lots: 1         #固定数量
            rate: 0         #挂单比例，配合byrate使用

    clear:                  #过期主力自动清理配置
        active: false       #是否启用

-   active: true    #是否启用
    id: exec2        #执行器id，不可重复
    trader: simnow2  #执行器绑定的交易通道id，如果不存在，无法执行
    scale: 1        #数量放大倍数，即该执行器的目标仓位，是组合理论目标仓位的多少倍，可以为小数 

    policy:         #执行单元分配策略，系统根据该策略创建对一个的执行单元
        default:    #默认策略，根据品种ID设置，如SHFE.rb，如果没有针对品种设置，则使用默认策略
            name: WtExeFact.WtMinImpactExeUnit #执行单元名称
            offset: 0       #委托价偏移跳数
            expire: 5       #订单超时没秒数
            pricemode: 1    #基础价格模式，-1-己方最优，0-最新价，1-对手价
            span: 500       #下单时间间隔（tick驱动的）
            byrate: false   #是否按对手盘挂单量的比例挂单，配合rate使用
            lots: 1         #固定数量
            rate: 0         #挂单比例，配合byrate使用

    clear:                  #过期主力自动清理配置
        active: false       #是否启用
```
