### DISCUSSION TITLE
数据组件是否可以控制只落地指定的数据类型

### DISCUSSION THREAD

**Discussion by puddingsmall** [wondertrader/wondertrader#53] [Q&A] [answered]
数据组件是否可以控制只落地指定的数据类型

**Comment by wondertrader** [comment, marked as answer]
```yaml
writer:
    module: WtDtStorage #数据存储模块
    async: true         #同步落地还是异步落地，期货推荐同步，股票推荐异步
    groupsize: 20       #日志分组大小，主要用于控制日志输出，当订阅合约较多时，推荐1000以上，当订阅的合约数较少时，推荐100以内
    path: ../STK_Data   #数据存储的路径
    savelog: false      #是否保存tick到csv
    disabletick: false    #不保存tick数据，默认false
    disablemin1: false    #不保存min1数据，默认false
    disablemin5: false    #不保存min5数据，默认false
    disableday: false     #不保存day数据，默认false
    disabletrans: false   #不保存股票l2逐笔成交数据，默认false
    disableordque: false  #不保存股票l2委托队列数据，默认false
    disableorddtl: false  #不保存股票l2逐笔委托数据，默认false
```
数据组件的配置文件进行控制
